#!/usr/bin/env python3
"""Generate morphology/distribution candidates without assigning translations."""
import argparse,hashlib,json,re
from collections import Counter,defaultdict
from pathlib import Path
BLOB='2a4533ab9bdfa85db9bad602d590978953055df1'
def gitblob(b):return hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--corpus',type=Path,required=True);p.add_argument('--out',type=Path,required=True);p.add_argument('--min-count',type=int,default=8);a=p.parse_args();b=a.corpus.read_bytes()
 if gitblob(b)!=BLOB:raise SystemExit('Corpus blob mismatch')
 toks=[];locs=defaultdict(list);left=defaultdict(Counter);right=defaultdict(Counter);initial=Counter();final=Counter()
 for line in b.decode().splitlines():
  m=re.match(r'^<([^>]+)>\s*(.*)$',line)
  if not m:continue
  locus,text=m.groups();clean=re.sub(r'<[^>]*>','',text)
  if ',' in text or '<->' in text or not re.fullmatch(r'[a-z.\s]+',clean):continue
  w=[x for x in re.split(r'[.\s]+',clean.strip()) if x]
  for i,x in enumerate(w):
   toks.append(x);locs[x].append(locus)
   if i:left[x][w[i-1]]+=1
   if i+1<len(w):right[x][w[i+1]]+=1
   initial[x[0]]+=1;final[x[-1]]+=1
 freq=Counter(toks);vocab=list(freq)
 def family(x):
  near=[]
  for y in vocab:
   if x==y:continue
   if len(x)>=3 and len(y)>=3 and (x[:3]==y[:3] or x[-3:]==y[-3:]):near.append((freq[y],y))
  return [y for _,y in sorted(near,reverse=True)[:12]]
 candidates=[]
 for x,n in freq.most_common():
  if n<a.min_count:break
  candidates.append({'eva':x,'count':n,'sample_loci':locs[x][:12],'prefix2':x[:2],'suffix2':x[-2:],'morphological_family':family(x),'left_neighbors':left[x].most_common(8),'right_neighbors':right[x].most_common(8),'candidate_meanings':[],'nonsemantic_alternative':'frequency/morphotactic/section effect','status':'NOT_RUN'})
 out={'classification':'WILD_MORPHOLOGY_CANDIDATE_GENERATION_NOT_TRANSLATION','source_blob':BLOB,'token_count':len(toks),'vocabulary':len(freq),'candidates':candidates,'rule':'No gloss is generated by this script; meanings require independent visual/context constraints and held-out prediction.'}
 a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'token_count':len(toks),'vocabulary':len(freq),'candidate_count':len(candidates)},indent=2))
if __name__=='__main__':main()
